grafana:
  adminPassword: prom-operator

  ## Passed to grafana subchart and used by servicemonitor below
  ##
  service:
    enabled: true
    type: LoadBalancer
    port: 3000
    targetPort: 3000
      # targetPort: 4181 To be used with a proxy extraContainer
    annotations: {}
    labels: {}
    portName: service
  ## If true, create a serviceMonitor for grafana
  ##
## Deploy a Prometheus instance
##
prometheus:
  service:
    port: 9090
    targetPort: 9090
    type: LoadBalancer
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    #scraping-gpu-metrics
    additionalScrapeConfigs:
    - job_name: gpu-metrics
      scrape_interval: 1s
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - gpu-operator-resources
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: kubernetes_node
  additionalServiceMonitors:
  # Name of the ServiceMonitor to create
  # for jupyterhub_metrics
  - name: "jhub-https-service"
    namespaceSelector:
      matchNames:
      - "jhub"
    selector:
      matchLabels:
        component: proxy-public
    endpoints:
    - targetPort: https
      path: /hub/metrics
      scheme: https
      #can be disable. This is for developemnt where the ssl cert is self signed
      tlsConfig:
        insecureSkipVerify: true