kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: cinder-storage
provisioner: kubernetes.io/cinder
parameters:
  availability: ceph
