- name: Create Cluster Template
  openstack.cloud.coe_cluster_template:
    cloud: "{{ cloud_name_var }}"
    coe: kubernetes
    name: "{{ cluster_name }}_template"
    image_id: "fedora-coreos-latest"
    docker_volume_size: "{{ docker_volume_size_gb }}"
    external_network_id: External
    floating_ip_enabled: false
    master_lb_enabled: yes
    volume_driver: cinder
    state: present

- name: Init k8s stack
  openstack.cloud.coe_cluster:
    cloud: "{{ cloud_name_var }}"
    name: "{{ cluster_name }}"
    cluster_template_id: "{{ cluster_name }}_template"
    master_flavor_id: "{{ master_flavor }}"
    flavor_id: "{{ worker_flavor }}"
    keypair: "{{ keypair_name }}"
    master_count: "{{ num_masters }}"
    node_count: "{{ num_workers }}"
    state: present
    labels:
      admission_control_list: "{{ admission_plugins }}"
      # does not play nice with our custom admission plugins, causing a heat creation error due to 'timeout' (likely pre-empted)
      kube_dashboard_enabled: false
      auto_healing_enable: true
      auto_scaling_enabled: true
      master_lb_floating_ip_enabled: true
      max_node_count: "{{ max_worker_nodes }}"
      container_infra_prefix: "{{ mirror_url }}"
      flannel_backend: host-gw
      autoscaler_tag: "{{ cluster_autoscaler_version }}"
      kube_tag: "{{ kube_tag }}"
      etcd_tag: "{{ etcd_tag }}"
  register: stack_result
