# COE module does not support node groups yet, lets do it by hand....
- name: Wait for Cluster Creation
  command: "openstack --os-cloud={{ cloud_name_var }} coe cluster show {{ cluster_name }}"
  register: cluster_status_result
  until: '"COMPLETE" in cluster_status_result.stdout'
  retries: 120
  delay: 10 # Wait for 20 minutes

- name: Check if GPU Node Group has been added
  command: "openstack --os-cloud={{ cloud_name_var }} coe nodegroup list {{ cluster_name }}"
  register: node_group_result

- name: Add GPU Node Group (through Openstack CLI)
  # Were forced to create 1 node for the group
  # We should add '--merge-labels' before --labels in a future openstack which supports it
  command: >
    openstack --os-cloud={{ cloud_name_var }} coe nodegroup create {{ cluster_name }} gpu-worker
    --min-nodes 1 --node-count 1 --max-nodes {{ max_gpu_nodes }} --role gpu --flavor {{ gpu_flavor }}
    --labels kubelet_options='--register-with-taints={{ gpu_taint }}'
  when: '"gpu-worker" not in node_group_result.stdout'
