- hosts: localhost # Kubectl is configured from this machine
  roles:
    - deploy_jhub
  vars:
    # Helm name of the service
    jhub_deployed_name: jhub
    # K8s namespace
    jhub_namespace: jhub
    # Helm chart version for Jhub
    jhub_version: "0.11.1"

    # Even if you don't use GPUs we deploy the Nvidia GPU operator
    # for simplicity (otherwise we need another var to enable GPU support across notebooks).

    # This version needs have been built by running playbooks/build_gpu_driver.yml beforehand
    NVIDIA_DRIVER_VERSION: 460.32.03
